### ISSUE TITLE
Touch compatible

### ISSUE THREAD

**Issue by gauravshrestha** [chrispahm/chartjs-plugin-dragData#20] opened 2019-04-04 03:13 UTC
I am using this in an angular 7 application and it works fine in a PC but I can't get it to work on an iPad.  Here is a stackblitz of the example: https://stackblitz.com/edit/ng2-charts-g  .  Is touch fully supported on this?

Thank you.

**Comment by chrispahm** [comment] 2019-04-04 06:54
Hi @gauravshrestha, thanks for pointing this out.

Touch is fully supported (at least it should be). I bet you already know this, but you can test most of the popular Touch devices from the convenience of your browser by toggling the "Device Toolbar" in the Chrome Developer Console 
![image](https://user-images.githubusercontent.com/20703207/55535028-371a0700-56b6-11e9-9e93-e75ed90959ac.png)
![image](https://user-images.githubusercontent.com/20703207/55535067-544ed580-56b6-11e9-8346-021c9275a7e1.png)
Always make sure to reload the page at least once when switiching from standard (PC) mode to Touch Device mode.

What you should note though, is that by default the `pointHitRadius` of a Chart.js data point is to small to be correctly handled by touch devices. I would at least set a `pointHitRadius` of 25px, you can read more about [that topic here](https://www.smashingmagazine.com/2012/02/finger-friendly-design-ideal-mobile-touchscreen-target-sizes/). Also, I do recommend to increase the `pointSize` a little further, which helps indicate that the point is indeed dragablle.

For demonstration purposes, I made a fork of your example and added the `pointHitRadius` as explained above. 
[https://stackblitz.com/edit/ng2-charts-g-ijg7vb](https://stackblitz.com/edit/ng2-charts-g-ijg7vb)
and here for the live demo
[https://ng2-charts-g-ijg7vb.stackblitz.io](https://ng2-charts-g-ijg7vb.stackblitz.io)

Hope this helps!
Best
Christoph

**Comment by gauravshrestha** [comment] 2019-04-04 13:04
Christoph,

I really appreciate your response. I do however have another question. I
took your live demo at https://ng2-charts-g-ijg7vb.stackblitz.io/ and then
loaded it in iPad emulation mode using Chrome's dev tool.  The drag worked
but I get this error "Unable to preventDefault inside passive event
listener invocation." on the console.  Is there a way around this?  Also on
an actual iPad, using the live demo below the screen moves when the points
are being dragged, do you have any suggestion for this?

Thank you so much.

Kind regards

Gaurav

[image: image.png]

**Comment by chrispahm** [comment] 2019-04-04 14:18
Hey Gaurav,

1) Regarding the `console.error` in the Chrome DevTools: I only did a quick search, as I couldn't reproduce the error with any of the examples that are shared in this repo (e.g. try with [this one](https://chrispahm.github.io/chartjs-plugin-dragData/)). I'm guessing this is only occuring when a mobile device is emulated in Chrome though, and may also have to do with the way the application is bundled. There's more on the topic [here](https://developers.google.com/web/updates/2017/01/scrolling-intervention). As we don't call `preventDefault` directly in our code (this is done by the `d3` library in the background), you would need to have a deeper look of what is happening there.

2) The second problem you are describing is a general design issue and not so easy to solve. When a user touches the `canvas` area, it is certainly difficult to find out if the user just wants to scroll the page, or drag an element. The `canvas` element therefore has a `touch-action: none` CSS rule applied to it when called on a mobile device (you can observe this in the Chrome DevTools). Generally, the problem shouldn't occur with charts that are smaller than the viewport area. 
I updated the example to better fit the iPads Viewport:
[https://ng2-charts-g-ijg7vb.stackblitz.io/](https://ng2-charts-g-ijg7vb.stackblitz.io/)

From a UI perspective, I can't think of a scenario where I would ever want a chart larger than the actual viewport. However, that's outside the scope of this library.

Best
Christoph

**Comment by gauravshrestha** [comment] 2019-04-04 20:17
Thanks Christoph for you kind reply.  I have one last question.  On the
stackblitz example on https://stackblitz.com/edit/ng2-charts-g , would it
be possible to make the points on the x-axis at 100 and 200 draggable but
points the 300 and 400 be not draggable?

Thanks again

[image: image.png]

**Comment by chrispahm** [comment] 2019-04-05 07:53
Yes, you can simply return `false` in the `onDragStart` function. In your case, you would return `false` for any `element._index` larger than 1.
See [https://stackblitz.com/edit/ng2-charts-g-x5yjyr](https://stackblitz.com/edit/ng2-charts-g-x5yjyr).

May I close this question as answered then?

**Comment by gauravshrestha** [comment] 2019-04-05 13:23
Sure.

Thank you again.

**Closed** 2019-04-05 13:54 UTC
Labels: question

**Comment by bptremblay** [comment] 2021-03-18 02:35
The scrolling issue seems to be a common problem with canvas and svg elements.
The fact is, it's very normal to want to display charts inline on a scrolling page with lots of content above and below; especially on mobile where vertical space is the only option. 
A chart absolutely must respond correctly to scrolling-by-touch, because you can't put a note on the screen saying "please try swiping up or down on the white area around the chart".  In such cases, the chart most likely is not "interactive" with tooltips and such. It's one of several charts and the user wants to scroll up and down to see them all.
