### ISSUE TITLE
Radar Chart

### ISSUE THREAD

**Issue by speendo** [chrispahm/chartjs-plugin-dragData#6] opened 2018-07-24 10:03 UTC
Is there a way to make this work with a radar chart?

Because I don't manage to make it work and I don't know if it's me or the plugin ;)

**Comment by chrispahm** [comment] 2018-08-26 15:26
Currently, this plugin only works for line charts and bubble charts (since the last update). I tried to get radar charts to work as well but it seams that the `getValueForPixel` method always returns `undefined` when called on a radard chart scale. This could a) be a bug or b) intended behaviour. Anyways I'm going to open an issue on the chart.js main repo.

**Comment by lukaiser** [comment] 2018-12-21 13:15
Any news here? I looked for your ticket on the chart.js main repo and didn't find it. As far as I know, there currently isn't a `getValueForPixel` method for the radial scale.

**Comment by chrispahm** [comment] 2018-12-21 14:48
Hey there. Sorry, I totally forgot about actually opening the issue in the main repo back then. I just did it though, you can follow the progress [here](https://github.com/chartjs/Chart.js/issues/5931).   
A problem is, I (currently) don't have any use case for radar charts, so I don't have the time to be digging too much into the underlying problem.   
If this is feature is of particular interest for you, I guess looking around the current implementation in the [`scale.linear`](https://github.com/chartjs/Chart.js/blob/master/src/scales/scale.linear.js)  file in the `chartjs` main repo
```js
getValueForPixel: function(pixel) {
  var me = this;
  var isHorizontal = me.isHorizontal();
  var innerDimension = isHorizontal ? me.width : me.height;
  var offset = (isHorizontal ? pixel - me.left : me.bottom - pixel) / innerDimension;
  return me.start + ((me.end - me.start) * offset);
}
```
and adapting this logic to the [`scale.radialLinear`](https://github.com/chartjs/Chart.js/blob/master/src/scales/scale.radialLinear.js) file would be my best bet to get started.

**Comment by lukaiser** [comment] 2018-12-21 15:54
I created a pull request #16 with a workaround for now. If we get getValueForPixel, I will change.

**Comment by chrispahm** [comment] 2019-02-07 09:35
Alright everyone, I just merged the PR from @lukaiser, thanks again for that! Radar charts should be working from now one. [Click for a demo](https://chrispahm.github.io/chartjs-plugin-dragData/radar.html)

**Closed by chrispahm** 2019-02-07 09:35 UTC

**Comment by fazlay** [comment] 2022-09-14 17:34
> I created a pull request #16 with a workaround for now. If we get getValueForPixel, I will change.

@lukaiser Hi , could you please describe the problem and solution bit more elaborately ? . i'm working with pie chart, showing same error .

**Comment by lukaiser** [comment] 2022-09-14 19:53
@fazlay I am sorry, I can't help you. My comment and pull request is almost 4 years old. I haven't worked on it since then.
